# Generated by Django 4.1.7 on 2023-06-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechaSeminario', models.DateField()),
                ('empresaInstitucion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
    ]
